/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sx.icecap.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DataPackStructure service. Represents a row in the &quot;SX_ICECAP_DataPackStructure&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.sx.icecap.model.impl.DataPackStructureModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.sx.icecap.model.impl.DataPackStructureImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DataPackStructure
 * @generated
 */
@ProviderType
public interface DataPackStructureModel extends BaseModel<DataPackStructure> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a data pack structure model instance should use the {@link DataPackStructure} interface instead.
	 */

	/**
	 * Returns the primary key of this data pack structure.
	 *
	 * @return the primary key of this data pack structure
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this data pack structure.
	 *
	 * @param primaryKey the primary key of this data pack structure
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the data pack ID of this data pack structure.
	 *
	 * @return the data pack ID of this data pack structure
	 */
	public long getDataPackId();

	/**
	 * Sets the data pack ID of this data pack structure.
	 *
	 * @param dataPackId the data pack ID of this data pack structure
	 */
	public void setDataPackId(long dataPackId);

	/**
	 * Returns the structure of this data pack structure.
	 *
	 * @return the structure of this data pack structure
	 */
	@AutoEscape
	public String getStructure();

	/**
	 * Sets the structure of this data pack structure.
	 *
	 * @param structure the structure of this data pack structure
	 */
	public void setStructure(String structure);

}