/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sx.icecap.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import com.sx.icecap.model.DataType;
import com.sx.icecap.model.DataTypeModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DataType service. Represents a row in the &quot;SX_ICECAP_DataType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DataTypeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DataTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DataTypeImpl
 * @generated
 */
public class DataTypeModelImpl
	extends BaseModelImpl<DataType> implements DataTypeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a data type model instance should use the <code>DataType</code> interface instead.
	 */
	public static final String TABLE_NAME = "SX_ICECAP_DataType";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"dataTypeId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"dataTypeName", Types.VARCHAR}, {"dataTypeVersion", Types.VARCHAR},
		{"displayName", Types.VARCHAR}, {"extension", Types.VARCHAR},
		{"sampleFileId", Types.BIGINT}, {"description", Types.VARCHAR},
		{"tooltip", Types.VARCHAR}, {"hasDataStructure", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dataTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dataTypeName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dataTypeVersion", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("displayName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("extension", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sampleFileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tooltip", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("hasDataStructure", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SX_ICECAP_DataType (uuid_ VARCHAR(75) null,dataTypeId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,dataTypeName VARCHAR(75) null,dataTypeVersion VARCHAR(75) null,displayName STRING null,extension VARCHAR(75) null,sampleFileId LONG,description STRING null,tooltip STRING null,hasDataStructure BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table SX_ICECAP_DataType";

	public static final String ORDER_BY_JPQL =
		" ORDER BY dataType.dataTypeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SX_ICECAP_DataType.dataTypeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long DATATYPENAME_COLUMN_BITMASK = 2L;

	public static final long DATATYPEVERSION_COLUMN_BITMASK = 4L;

	public static final long GROUPID_COLUMN_BITMASK = 8L;

	public static final long STATUS_COLUMN_BITMASK = 16L;

	public static final long USERID_COLUMN_BITMASK = 32L;

	public static final long UUID_COLUMN_BITMASK = 64L;

	public static final long DATATYPEID_COLUMN_BITMASK = 128L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public DataTypeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _dataTypeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDataTypeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _dataTypeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DataType.class;
	}

	@Override
	public String getModelClassName() {
		return DataType.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DataType, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DataType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DataType, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((DataType)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DataType, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DataType, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DataType)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DataType, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DataType, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, DataType>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			DataType.class.getClassLoader(), DataType.class,
			ModelWrapper.class);

		try {
			Constructor<DataType> constructor =
				(Constructor<DataType>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<DataType, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<DataType, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<DataType, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<DataType, Object>>();
		Map<String, BiConsumer<DataType, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<DataType, ?>>();

		attributeGetterFunctions.put("uuid", DataType::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<DataType, String>)DataType::setUuid);
		attributeGetterFunctions.put("dataTypeId", DataType::getDataTypeId);
		attributeSetterBiConsumers.put(
			"dataTypeId", (BiConsumer<DataType, Long>)DataType::setDataTypeId);
		attributeGetterFunctions.put("companyId", DataType::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<DataType, Long>)DataType::setCompanyId);
		attributeGetterFunctions.put("groupId", DataType::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<DataType, Long>)DataType::setGroupId);
		attributeGetterFunctions.put("userId", DataType::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<DataType, Long>)DataType::setUserId);
		attributeGetterFunctions.put("userName", DataType::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<DataType, String>)DataType::setUserName);
		attributeGetterFunctions.put("createDate", DataType::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<DataType, Date>)DataType::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", DataType::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<DataType, Date>)DataType::setModifiedDate);
		attributeGetterFunctions.put("status", DataType::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<DataType, Integer>)DataType::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", DataType::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<DataType, Long>)DataType::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", DataType::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<DataType, String>)DataType::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", DataType::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate", (BiConsumer<DataType, Date>)DataType::setStatusDate);
		attributeGetterFunctions.put("dataTypeName", DataType::getDataTypeName);
		attributeSetterBiConsumers.put(
			"dataTypeName",
			(BiConsumer<DataType, String>)DataType::setDataTypeName);
		attributeGetterFunctions.put(
			"dataTypeVersion", DataType::getDataTypeVersion);
		attributeSetterBiConsumers.put(
			"dataTypeVersion",
			(BiConsumer<DataType, String>)DataType::setDataTypeVersion);
		attributeGetterFunctions.put("displayName", DataType::getDisplayName);
		attributeSetterBiConsumers.put(
			"displayName",
			(BiConsumer<DataType, String>)DataType::setDisplayName);
		attributeGetterFunctions.put("extension", DataType::getExtension);
		attributeSetterBiConsumers.put(
			"extension", (BiConsumer<DataType, String>)DataType::setExtension);
		attributeGetterFunctions.put("sampleFileId", DataType::getSampleFileId);
		attributeSetterBiConsumers.put(
			"sampleFileId",
			(BiConsumer<DataType, Long>)DataType::setSampleFileId);
		attributeGetterFunctions.put("description", DataType::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<DataType, String>)DataType::setDescription);
		attributeGetterFunctions.put("tooltip", DataType::getTooltip);
		attributeSetterBiConsumers.put(
			"tooltip", (BiConsumer<DataType, String>)DataType::setTooltip);
		attributeGetterFunctions.put(
			"hasDataStructure", DataType::getHasDataStructure);
		attributeSetterBiConsumers.put(
			"hasDataStructure",
			(BiConsumer<DataType, Boolean>)DataType::setHasDataStructure);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getDataTypeId() {
		return _dataTypeId;
	}

	@Override
	public void setDataTypeId(long dataTypeId) {
		_dataTypeId = dataTypeId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@Override
	public String getDataTypeName() {
		if (_dataTypeName == null) {
			return "";
		}
		else {
			return _dataTypeName;
		}
	}

	@Override
	public void setDataTypeName(String dataTypeName) {
		_columnBitmask |= DATATYPENAME_COLUMN_BITMASK;

		if (_originalDataTypeName == null) {
			_originalDataTypeName = _dataTypeName;
		}

		_dataTypeName = dataTypeName;
	}

	public String getOriginalDataTypeName() {
		return GetterUtil.getString(_originalDataTypeName);
	}

	@Override
	public String getDataTypeVersion() {
		if (_dataTypeVersion == null) {
			return "";
		}
		else {
			return _dataTypeVersion;
		}
	}

	@Override
	public void setDataTypeVersion(String dataTypeVersion) {
		_columnBitmask |= DATATYPEVERSION_COLUMN_BITMASK;

		if (_originalDataTypeVersion == null) {
			_originalDataTypeVersion = _dataTypeVersion;
		}

		_dataTypeVersion = dataTypeVersion;
	}

	public String getOriginalDataTypeVersion() {
		return GetterUtil.getString(_originalDataTypeVersion);
	}

	@Override
	public String getDisplayName() {
		if (_displayName == null) {
			return "";
		}
		else {
			return _displayName;
		}
	}

	@Override
	public String getDisplayName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDisplayName(languageId);
	}

	@Override
	public String getDisplayName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDisplayName(languageId, useDefault);
	}

	@Override
	public String getDisplayName(String languageId) {
		return LocalizationUtil.getLocalization(getDisplayName(), languageId);
	}

	@Override
	public String getDisplayName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getDisplayName(), languageId, useDefault);
	}

	@Override
	public String getDisplayNameCurrentLanguageId() {
		return _displayNameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDisplayNameCurrentValue() {
		Locale locale = getLocale(_displayNameCurrentLanguageId);

		return getDisplayName(locale);
	}

	@Override
	public Map<Locale, String> getDisplayNameMap() {
		return LocalizationUtil.getLocalizationMap(getDisplayName());
	}

	@Override
	public void setDisplayName(String displayName) {
		_displayName = displayName;
	}

	@Override
	public void setDisplayName(String displayName, Locale locale) {
		setDisplayName(displayName, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDisplayName(
		String displayName, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(displayName)) {
			setDisplayName(
				LocalizationUtil.updateLocalization(
					getDisplayName(), "DisplayName", displayName, languageId,
					defaultLanguageId));
		}
		else {
			setDisplayName(
				LocalizationUtil.removeLocalization(
					getDisplayName(), "DisplayName", languageId));
		}
	}

	@Override
	public void setDisplayNameCurrentLanguageId(String languageId) {
		_displayNameCurrentLanguageId = languageId;
	}

	@Override
	public void setDisplayNameMap(Map<Locale, String> displayNameMap) {
		setDisplayNameMap(displayNameMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDisplayNameMap(
		Map<Locale, String> displayNameMap, Locale defaultLocale) {

		if (displayNameMap == null) {
			return;
		}

		setDisplayName(
			LocalizationUtil.updateLocalization(
				displayNameMap, getDisplayName(), "DisplayName",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getExtension() {
		if (_extension == null) {
			return "";
		}
		else {
			return _extension;
		}
	}

	@Override
	public void setExtension(String extension) {
		_extension = extension;
	}

	@Override
	public long getSampleFileId() {
		return _sampleFileId;
	}

	@Override
	public void setSampleFileId(long sampleFileId) {
		_sampleFileId = sampleFileId;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public String getDescription(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId);
	}

	@Override
	public String getDescription(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId, useDefault);
	}

	@Override
	public String getDescription(String languageId) {
		return LocalizationUtil.getLocalization(getDescription(), languageId);
	}

	@Override
	public String getDescription(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getDescription(), languageId, useDefault);
	}

	@Override
	public String getDescriptionCurrentLanguageId() {
		return _descriptionCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDescriptionCurrentValue() {
		Locale locale = getLocale(_descriptionCurrentLanguageId);

		return getDescription(locale);
	}

	@Override
	public Map<Locale, String> getDescriptionMap() {
		return LocalizationUtil.getLocalizationMap(getDescription());
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public void setDescription(String description, Locale locale) {
		setDescription(description, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescription(
		String description, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(description)) {
			setDescription(
				LocalizationUtil.updateLocalization(
					getDescription(), "Description", description, languageId,
					defaultLanguageId));
		}
		else {
			setDescription(
				LocalizationUtil.removeLocalization(
					getDescription(), "Description", languageId));
		}
	}

	@Override
	public void setDescriptionCurrentLanguageId(String languageId) {
		_descriptionCurrentLanguageId = languageId;
	}

	@Override
	public void setDescriptionMap(Map<Locale, String> descriptionMap) {
		setDescriptionMap(descriptionMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale) {

		if (descriptionMap == null) {
			return;
		}

		setDescription(
			LocalizationUtil.updateLocalization(
				descriptionMap, getDescription(), "Description",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getTooltip() {
		if (_tooltip == null) {
			return "";
		}
		else {
			return _tooltip;
		}
	}

	@Override
	public String getTooltip(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTooltip(languageId);
	}

	@Override
	public String getTooltip(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTooltip(languageId, useDefault);
	}

	@Override
	public String getTooltip(String languageId) {
		return LocalizationUtil.getLocalization(getTooltip(), languageId);
	}

	@Override
	public String getTooltip(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getTooltip(), languageId, useDefault);
	}

	@Override
	public String getTooltipCurrentLanguageId() {
		return _tooltipCurrentLanguageId;
	}

	@JSON
	@Override
	public String getTooltipCurrentValue() {
		Locale locale = getLocale(_tooltipCurrentLanguageId);

		return getTooltip(locale);
	}

	@Override
	public Map<Locale, String> getTooltipMap() {
		return LocalizationUtil.getLocalizationMap(getTooltip());
	}

	@Override
	public void setTooltip(String tooltip) {
		_tooltip = tooltip;
	}

	@Override
	public void setTooltip(String tooltip, Locale locale) {
		setTooltip(tooltip, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTooltip(
		String tooltip, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(tooltip)) {
			setTooltip(
				LocalizationUtil.updateLocalization(
					getTooltip(), "Tooltip", tooltip, languageId,
					defaultLanguageId));
		}
		else {
			setTooltip(
				LocalizationUtil.removeLocalization(
					getTooltip(), "Tooltip", languageId));
		}
	}

	@Override
	public void setTooltipCurrentLanguageId(String languageId) {
		_tooltipCurrentLanguageId = languageId;
	}

	@Override
	public void setTooltipMap(Map<Locale, String> tooltipMap) {
		setTooltipMap(tooltipMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTooltipMap(
		Map<Locale, String> tooltipMap, Locale defaultLocale) {

		if (tooltipMap == null) {
			return;
		}

		setTooltip(
			LocalizationUtil.updateLocalization(
				tooltipMap, getTooltip(), "Tooltip",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public boolean getHasDataStructure() {
		return _hasDataStructure;
	}

	@Override
	public boolean isHasDataStructure() {
		return _hasDataStructure;
	}

	@Override
	public void setHasDataStructure(boolean hasDataStructure) {
		_hasDataStructure = hasDataStructure;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(DataType.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), DataType.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> displayNameMap = getDisplayNameMap();

		for (Map.Entry<Locale, String> entry : displayNameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> descriptionMap = getDescriptionMap();

		for (Map.Entry<Locale, String> entry : descriptionMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> tooltipMap = getTooltipMap();

		for (Map.Entry<Locale, String> entry : tooltipMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getDisplayName();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			DataType.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String displayName = getDisplayName(defaultLocale);

		if (Validator.isNull(displayName)) {
			setDisplayName(
				getDisplayName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setDisplayName(
				getDisplayName(defaultLocale), defaultLocale, defaultLocale);
		}

		String description = getDescription(defaultLocale);

		if (Validator.isNull(description)) {
			setDescription(
				getDescription(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setDescription(
				getDescription(defaultLocale), defaultLocale, defaultLocale);
		}

		String tooltip = getTooltip(defaultLocale);

		if (Validator.isNull(tooltip)) {
			setTooltip(getTooltip(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setTooltip(getTooltip(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public DataType toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DataType>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DataTypeImpl dataTypeImpl = new DataTypeImpl();

		dataTypeImpl.setUuid(getUuid());
		dataTypeImpl.setDataTypeId(getDataTypeId());
		dataTypeImpl.setCompanyId(getCompanyId());
		dataTypeImpl.setGroupId(getGroupId());
		dataTypeImpl.setUserId(getUserId());
		dataTypeImpl.setUserName(getUserName());
		dataTypeImpl.setCreateDate(getCreateDate());
		dataTypeImpl.setModifiedDate(getModifiedDate());
		dataTypeImpl.setStatus(getStatus());
		dataTypeImpl.setStatusByUserId(getStatusByUserId());
		dataTypeImpl.setStatusByUserName(getStatusByUserName());
		dataTypeImpl.setStatusDate(getStatusDate());
		dataTypeImpl.setDataTypeName(getDataTypeName());
		dataTypeImpl.setDataTypeVersion(getDataTypeVersion());
		dataTypeImpl.setDisplayName(getDisplayName());
		dataTypeImpl.setExtension(getExtension());
		dataTypeImpl.setSampleFileId(getSampleFileId());
		dataTypeImpl.setDescription(getDescription());
		dataTypeImpl.setTooltip(getTooltip());
		dataTypeImpl.setHasDataStructure(isHasDataStructure());

		dataTypeImpl.resetOriginalValues();

		return dataTypeImpl;
	}

	@Override
	public int compareTo(DataType dataType) {
		long primaryKey = dataType.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DataType)) {
			return false;
		}

		DataType dataType = (DataType)object;

		long primaryKey = dataType.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalUserId = _userId;

		_setOriginalUserId = false;

		_setModifiedDate = false;
		_originalStatus = _status;

		_setOriginalStatus = false;

		_originalDataTypeName = _dataTypeName;

		_originalDataTypeVersion = _dataTypeVersion;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DataType> toCacheModel() {
		DataTypeCacheModel dataTypeCacheModel = new DataTypeCacheModel();

		dataTypeCacheModel.uuid = getUuid();

		String uuid = dataTypeCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			dataTypeCacheModel.uuid = null;
		}

		dataTypeCacheModel.dataTypeId = getDataTypeId();

		dataTypeCacheModel.companyId = getCompanyId();

		dataTypeCacheModel.groupId = getGroupId();

		dataTypeCacheModel.userId = getUserId();

		dataTypeCacheModel.userName = getUserName();

		String userName = dataTypeCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			dataTypeCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			dataTypeCacheModel.createDate = createDate.getTime();
		}
		else {
			dataTypeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			dataTypeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			dataTypeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		dataTypeCacheModel.status = getStatus();

		dataTypeCacheModel.statusByUserId = getStatusByUserId();

		dataTypeCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = dataTypeCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			dataTypeCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			dataTypeCacheModel.statusDate = statusDate.getTime();
		}
		else {
			dataTypeCacheModel.statusDate = Long.MIN_VALUE;
		}

		dataTypeCacheModel.dataTypeName = getDataTypeName();

		String dataTypeName = dataTypeCacheModel.dataTypeName;

		if ((dataTypeName != null) && (dataTypeName.length() == 0)) {
			dataTypeCacheModel.dataTypeName = null;
		}

		dataTypeCacheModel.dataTypeVersion = getDataTypeVersion();

		String dataTypeVersion = dataTypeCacheModel.dataTypeVersion;

		if ((dataTypeVersion != null) && (dataTypeVersion.length() == 0)) {
			dataTypeCacheModel.dataTypeVersion = null;
		}

		dataTypeCacheModel.displayName = getDisplayName();

		String displayName = dataTypeCacheModel.displayName;

		if ((displayName != null) && (displayName.length() == 0)) {
			dataTypeCacheModel.displayName = null;
		}

		dataTypeCacheModel.extension = getExtension();

		String extension = dataTypeCacheModel.extension;

		if ((extension != null) && (extension.length() == 0)) {
			dataTypeCacheModel.extension = null;
		}

		dataTypeCacheModel.sampleFileId = getSampleFileId();

		dataTypeCacheModel.description = getDescription();

		String description = dataTypeCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			dataTypeCacheModel.description = null;
		}

		dataTypeCacheModel.tooltip = getTooltip();

		String tooltip = dataTypeCacheModel.tooltip;

		if ((tooltip != null) && (tooltip.length() == 0)) {
			dataTypeCacheModel.tooltip = null;
		}

		dataTypeCacheModel.hasDataStructure = isHasDataStructure();

		return dataTypeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DataType, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DataType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DataType, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((DataType)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<DataType, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<DataType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DataType, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((DataType)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DataType>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _dataTypeId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _dataTypeName;
	private String _originalDataTypeName;
	private String _dataTypeVersion;
	private String _originalDataTypeVersion;
	private String _displayName;
	private String _displayNameCurrentLanguageId;
	private String _extension;
	private long _sampleFileId;
	private String _description;
	private String _descriptionCurrentLanguageId;
	private String _tooltip;
	private String _tooltipCurrentLanguageId;
	private boolean _hasDataStructure;
	private long _columnBitmask;
	private DataType _escapedModel;

}