/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sx.icecap.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.sx.icecap.model.DataPackStructure;
import com.sx.icecap.model.DataPackStructureModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DataPackStructure service. Represents a row in the &quot;SX_ICECAP_DataPackStructure&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DataPackStructureModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DataPackStructureImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DataPackStructureImpl
 * @generated
 */
public class DataPackStructureModelImpl
	extends BaseModelImpl<DataPackStructure> implements DataPackStructureModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a data pack structure model instance should use the <code>DataPackStructure</code> interface instead.
	 */
	public static final String TABLE_NAME = "SX_ICECAP_DataPackStructure";

	public static final Object[][] TABLE_COLUMNS = {
		{"dataPackId", Types.BIGINT}, {"structure", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("dataPackId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("structure", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SX_ICECAP_DataPackStructure (dataPackId LONG not null primary key,structure TEXT null)";

	public static final String TABLE_SQL_DROP =
		"drop table SX_ICECAP_DataPackStructure";

	public static final String ORDER_BY_JPQL =
		" ORDER BY dataPackStructure.dataPackId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SX_ICECAP_DataPackStructure.dataPackId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public DataPackStructureModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _dataPackId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDataPackId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _dataPackId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DataPackStructure.class;
	}

	@Override
	public String getModelClassName() {
		return DataPackStructure.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DataPackStructure, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DataPackStructure, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DataPackStructure, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DataPackStructure)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DataPackStructure, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DataPackStructure, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DataPackStructure)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DataPackStructure, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DataPackStructure, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, DataPackStructure>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			DataPackStructure.class.getClassLoader(), DataPackStructure.class,
			ModelWrapper.class);

		try {
			Constructor<DataPackStructure> constructor =
				(Constructor<DataPackStructure>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<DataPackStructure, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<DataPackStructure, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<DataPackStructure, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<DataPackStructure, Object>>();
		Map<String, BiConsumer<DataPackStructure, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<DataPackStructure, ?>>();

		attributeGetterFunctions.put(
			"dataPackId", DataPackStructure::getDataPackId);
		attributeSetterBiConsumers.put(
			"dataPackId",
			(BiConsumer<DataPackStructure, Long>)
				DataPackStructure::setDataPackId);
		attributeGetterFunctions.put(
			"structure", DataPackStructure::getStructure);
		attributeSetterBiConsumers.put(
			"structure",
			(BiConsumer<DataPackStructure, String>)
				DataPackStructure::setStructure);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getDataPackId() {
		return _dataPackId;
	}

	@Override
	public void setDataPackId(long dataPackId) {
		_dataPackId = dataPackId;
	}

	@JSON
	@Override
	public String getStructure() {
		if (_structure == null) {
			return "";
		}
		else {
			return _structure;
		}
	}

	@Override
	public void setStructure(String structure) {
		_structure = structure;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, DataPackStructure.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DataPackStructure toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DataPackStructure>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DataPackStructureImpl dataPackStructureImpl =
			new DataPackStructureImpl();

		dataPackStructureImpl.setDataPackId(getDataPackId());
		dataPackStructureImpl.setStructure(getStructure());

		dataPackStructureImpl.resetOriginalValues();

		return dataPackStructureImpl;
	}

	@Override
	public int compareTo(DataPackStructure dataPackStructure) {
		long primaryKey = dataPackStructure.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DataPackStructure)) {
			return false;
		}

		DataPackStructure dataPackStructure = (DataPackStructure)object;

		long primaryKey = dataPackStructure.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<DataPackStructure> toCacheModel() {
		DataPackStructureCacheModel dataPackStructureCacheModel =
			new DataPackStructureCacheModel();

		dataPackStructureCacheModel.dataPackId = getDataPackId();

		dataPackStructureCacheModel.structure = getStructure();

		String structure = dataPackStructureCacheModel.structure;

		if ((structure != null) && (structure.length() == 0)) {
			dataPackStructureCacheModel.structure = null;
		}

		return dataPackStructureCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DataPackStructure, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DataPackStructure, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DataPackStructure, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(DataPackStructure)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<DataPackStructure, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<DataPackStructure, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DataPackStructure, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((DataPackStructure)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DataPackStructure>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _dataPackId;
	private String _structure;
	private DataPackStructure _escapedModel;

}