/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sx.icecap.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.NoSuchModelException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import com.sx.icecap.model.Term;
import com.sx.icecap.model.TermModel;
import com.sx.icecap.model.TermSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Term service. Represents a row in the &quot;SX_ICECAP_Term&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TermModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TermImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TermImpl
 * @generated
 */
@JSON(strict = true)
public class TermModelImpl extends BaseModelImpl<Term> implements TermModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a term model instance should use the <code>Term</code> interface instead.
	 */
	public static final String TABLE_NAME = "SX_ICECAP_Term";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"termId", Types.BIGINT},
		{"groupTermId", Types.VARCHAR}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}, {"lastPublishDate", Types.TIMESTAMP},
		{"termName", Types.VARCHAR}, {"termVersion", Types.VARCHAR},
		{"termType", Types.VARCHAR}, {"displayName", Types.VARCHAR},
		{"definition", Types.VARCHAR}, {"tooltip", Types.VARCHAR},
		{"synonyms", Types.VARCHAR}, {"attributesJSON", Types.VARCHAR},
		{"standard", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("termId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupTermId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastPublishDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("termName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("termVersion", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("termType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("displayName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("definition", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tooltip", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("synonyms", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("attributesJSON", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("standard", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SX_ICECAP_Term (uuid_ VARCHAR(75) null,termId LONG not null primary key,groupTermId VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,lastPublishDate DATE null,termName VARCHAR(75) null,termVersion VARCHAR(75) null,termType VARCHAR(75) null,displayName STRING null,definition STRING null,tooltip STRING null,synonyms VARCHAR(512) null,attributesJSON TEXT null,standard BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table SX_ICECAP_Term";

	public static final String ORDER_BY_JPQL = " ORDER BY term.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SX_ICECAP_Term.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long STATUS_COLUMN_BITMASK = 4L;

	public static final long TERMNAME_COLUMN_BITMASK = 8L;

	public static final long TERMVERSION_COLUMN_BITMASK = 16L;

	public static final long USERID_COLUMN_BITMASK = 32L;

	public static final long UUID_COLUMN_BITMASK = 64L;

	public static final long CREATEDATE_COLUMN_BITMASK = 128L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Term toModel(TermSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Term model = new TermImpl();

		model.setUuid(soapModel.getUuid());
		model.setTermId(soapModel.getTermId());
		model.setGroupTermId(soapModel.getGroupTermId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setLastPublishDate(soapModel.getLastPublishDate());
		model.setTermName(soapModel.getTermName());
		model.setTermVersion(soapModel.getTermVersion());
		model.setTermType(soapModel.getTermType());
		model.setDisplayName(soapModel.getDisplayName());
		model.setDefinition(soapModel.getDefinition());
		model.setTooltip(soapModel.getTooltip());
		model.setSynonyms(soapModel.getSynonyms());
		model.setAttributesJSON(soapModel.getAttributesJSON());
		model.setStandard(soapModel.isStandard());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Term> toModels(TermSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Term> models = new ArrayList<Term>(soapModels.length);

		for (TermSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public TermModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _termId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTermId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _termId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Term.class;
	}

	@Override
	public String getModelClassName() {
		return Term.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Term, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Term, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Term, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Term)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Term, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Term, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Term)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Term, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Term, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Term>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Term.class.getClassLoader(), Term.class, ModelWrapper.class);

		try {
			Constructor<Term> constructor =
				(Constructor<Term>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Term, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Term, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Term, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Term, Object>>();
		Map<String, BiConsumer<Term, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Term, ?>>();

		attributeGetterFunctions.put("uuid", Term::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Term, String>)Term::setUuid);
		attributeGetterFunctions.put("termId", Term::getTermId);
		attributeSetterBiConsumers.put(
			"termId", (BiConsumer<Term, Long>)Term::setTermId);
		attributeGetterFunctions.put("groupTermId", Term::getGroupTermId);
		attributeSetterBiConsumers.put(
			"groupTermId", (BiConsumer<Term, String>)Term::setGroupTermId);
		attributeGetterFunctions.put("groupId", Term::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Term, Long>)Term::setGroupId);
		attributeGetterFunctions.put("companyId", Term::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Term, Long>)Term::setCompanyId);
		attributeGetterFunctions.put("userId", Term::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Term, Long>)Term::setUserId);
		attributeGetterFunctions.put("userName", Term::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Term, String>)Term::setUserName);
		attributeGetterFunctions.put("createDate", Term::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Term, Date>)Term::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Term::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Term, Date>)Term::setModifiedDate);
		attributeGetterFunctions.put("status", Term::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<Term, Integer>)Term::setStatus);
		attributeGetterFunctions.put("statusByUserId", Term::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId", (BiConsumer<Term, Long>)Term::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", Term::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<Term, String>)Term::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", Term::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate", (BiConsumer<Term, Date>)Term::setStatusDate);
		attributeGetterFunctions.put(
			"lastPublishDate", Term::getLastPublishDate);
		attributeSetterBiConsumers.put(
			"lastPublishDate",
			(BiConsumer<Term, Date>)Term::setLastPublishDate);
		attributeGetterFunctions.put("termName", Term::getTermName);
		attributeSetterBiConsumers.put(
			"termName", (BiConsumer<Term, String>)Term::setTermName);
		attributeGetterFunctions.put("termVersion", Term::getTermVersion);
		attributeSetterBiConsumers.put(
			"termVersion", (BiConsumer<Term, String>)Term::setTermVersion);
		attributeGetterFunctions.put("termType", Term::getTermType);
		attributeSetterBiConsumers.put(
			"termType", (BiConsumer<Term, String>)Term::setTermType);
		attributeGetterFunctions.put("displayName", Term::getDisplayName);
		attributeSetterBiConsumers.put(
			"displayName", (BiConsumer<Term, String>)Term::setDisplayName);
		attributeGetterFunctions.put("definition", Term::getDefinition);
		attributeSetterBiConsumers.put(
			"definition", (BiConsumer<Term, String>)Term::setDefinition);
		attributeGetterFunctions.put("tooltip", Term::getTooltip);
		attributeSetterBiConsumers.put(
			"tooltip", (BiConsumer<Term, String>)Term::setTooltip);
		attributeGetterFunctions.put("synonyms", Term::getSynonyms);
		attributeSetterBiConsumers.put(
			"synonyms", (BiConsumer<Term, String>)Term::setSynonyms);
		attributeGetterFunctions.put("attributesJSON", Term::getAttributesJSON);
		attributeSetterBiConsumers.put(
			"attributesJSON",
			(BiConsumer<Term, String>)Term::setAttributesJSON);
		attributeGetterFunctions.put("standard", Term::getStandard);
		attributeSetterBiConsumers.put(
			"standard", (BiConsumer<Term, Boolean>)Term::setStandard);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getTermId() {
		return _termId;
	}

	@Override
	public void setTermId(long termId) {
		_termId = termId;
	}

	@JSON
	@Override
	public String getGroupTermId() {
		if (_groupTermId == null) {
			return "";
		}
		else {
			return _groupTermId;
		}
	}

	@Override
	public void setGroupTermId(String groupTermId) {
		_groupTermId = groupTermId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public Date getLastPublishDate() {
		return _lastPublishDate;
	}

	@Override
	public void setLastPublishDate(Date lastPublishDate) {
		_lastPublishDate = lastPublishDate;
	}

	@JSON
	@Override
	public String getTermName() {
		if (_termName == null) {
			return "";
		}
		else {
			return _termName;
		}
	}

	@Override
	public void setTermName(String termName) {
		_columnBitmask |= TERMNAME_COLUMN_BITMASK;

		if (_originalTermName == null) {
			_originalTermName = _termName;
		}

		_termName = termName;
	}

	public String getOriginalTermName() {
		return GetterUtil.getString(_originalTermName);
	}

	@JSON
	@Override
	public String getTermVersion() {
		if (_termVersion == null) {
			return "";
		}
		else {
			return _termVersion;
		}
	}

	@Override
	public void setTermVersion(String termVersion) {
		_columnBitmask |= TERMVERSION_COLUMN_BITMASK;

		if (_originalTermVersion == null) {
			_originalTermVersion = _termVersion;
		}

		_termVersion = termVersion;
	}

	public String getOriginalTermVersion() {
		return GetterUtil.getString(_originalTermVersion);
	}

	@JSON
	@Override
	public String getTermType() {
		if (_termType == null) {
			return "";
		}
		else {
			return _termType;
		}
	}

	@Override
	public void setTermType(String termType) {
		_termType = termType;
	}

	@JSON
	@Override
	public String getDisplayName() {
		if (_displayName == null) {
			return "";
		}
		else {
			return _displayName;
		}
	}

	@Override
	public String getDisplayName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDisplayName(languageId);
	}

	@Override
	public String getDisplayName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDisplayName(languageId, useDefault);
	}

	@Override
	public String getDisplayName(String languageId) {
		return LocalizationUtil.getLocalization(getDisplayName(), languageId);
	}

	@Override
	public String getDisplayName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getDisplayName(), languageId, useDefault);
	}

	@Override
	public String getDisplayNameCurrentLanguageId() {
		return _displayNameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDisplayNameCurrentValue() {
		Locale locale = getLocale(_displayNameCurrentLanguageId);

		return getDisplayName(locale);
	}

	@Override
	public Map<Locale, String> getDisplayNameMap() {
		return LocalizationUtil.getLocalizationMap(getDisplayName());
	}

	@Override
	public void setDisplayName(String displayName) {
		_displayName = displayName;
	}

	@Override
	public void setDisplayName(String displayName, Locale locale) {
		setDisplayName(displayName, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDisplayName(
		String displayName, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(displayName)) {
			setDisplayName(
				LocalizationUtil.updateLocalization(
					getDisplayName(), "DisplayName", displayName, languageId,
					defaultLanguageId));
		}
		else {
			setDisplayName(
				LocalizationUtil.removeLocalization(
					getDisplayName(), "DisplayName", languageId));
		}
	}

	@Override
	public void setDisplayNameCurrentLanguageId(String languageId) {
		_displayNameCurrentLanguageId = languageId;
	}

	@Override
	public void setDisplayNameMap(Map<Locale, String> displayNameMap) {
		setDisplayNameMap(displayNameMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDisplayNameMap(
		Map<Locale, String> displayNameMap, Locale defaultLocale) {

		if (displayNameMap == null) {
			return;
		}

		setDisplayName(
			LocalizationUtil.updateLocalization(
				displayNameMap, getDisplayName(), "DisplayName",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getDefinition() {
		if (_definition == null) {
			return "";
		}
		else {
			return _definition;
		}
	}

	@Override
	public String getDefinition(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDefinition(languageId);
	}

	@Override
	public String getDefinition(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDefinition(languageId, useDefault);
	}

	@Override
	public String getDefinition(String languageId) {
		return LocalizationUtil.getLocalization(getDefinition(), languageId);
	}

	@Override
	public String getDefinition(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getDefinition(), languageId, useDefault);
	}

	@Override
	public String getDefinitionCurrentLanguageId() {
		return _definitionCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDefinitionCurrentValue() {
		Locale locale = getLocale(_definitionCurrentLanguageId);

		return getDefinition(locale);
	}

	@Override
	public Map<Locale, String> getDefinitionMap() {
		return LocalizationUtil.getLocalizationMap(getDefinition());
	}

	@Override
	public void setDefinition(String definition) {
		_definition = definition;
	}

	@Override
	public void setDefinition(String definition, Locale locale) {
		setDefinition(definition, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDefinition(
		String definition, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(definition)) {
			setDefinition(
				LocalizationUtil.updateLocalization(
					getDefinition(), "Definition", definition, languageId,
					defaultLanguageId));
		}
		else {
			setDefinition(
				LocalizationUtil.removeLocalization(
					getDefinition(), "Definition", languageId));
		}
	}

	@Override
	public void setDefinitionCurrentLanguageId(String languageId) {
		_definitionCurrentLanguageId = languageId;
	}

	@Override
	public void setDefinitionMap(Map<Locale, String> definitionMap) {
		setDefinitionMap(definitionMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDefinitionMap(
		Map<Locale, String> definitionMap, Locale defaultLocale) {

		if (definitionMap == null) {
			return;
		}

		setDefinition(
			LocalizationUtil.updateLocalization(
				definitionMap, getDefinition(), "Definition",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getTooltip() {
		if (_tooltip == null) {
			return "";
		}
		else {
			return _tooltip;
		}
	}

	@Override
	public String getTooltip(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTooltip(languageId);
	}

	@Override
	public String getTooltip(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTooltip(languageId, useDefault);
	}

	@Override
	public String getTooltip(String languageId) {
		return LocalizationUtil.getLocalization(getTooltip(), languageId);
	}

	@Override
	public String getTooltip(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getTooltip(), languageId, useDefault);
	}

	@Override
	public String getTooltipCurrentLanguageId() {
		return _tooltipCurrentLanguageId;
	}

	@JSON
	@Override
	public String getTooltipCurrentValue() {
		Locale locale = getLocale(_tooltipCurrentLanguageId);

		return getTooltip(locale);
	}

	@Override
	public Map<Locale, String> getTooltipMap() {
		return LocalizationUtil.getLocalizationMap(getTooltip());
	}

	@Override
	public void setTooltip(String tooltip) {
		_tooltip = tooltip;
	}

	@Override
	public void setTooltip(String tooltip, Locale locale) {
		setTooltip(tooltip, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTooltip(
		String tooltip, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(tooltip)) {
			setTooltip(
				LocalizationUtil.updateLocalization(
					getTooltip(), "Tooltip", tooltip, languageId,
					defaultLanguageId));
		}
		else {
			setTooltip(
				LocalizationUtil.removeLocalization(
					getTooltip(), "Tooltip", languageId));
		}
	}

	@Override
	public void setTooltipCurrentLanguageId(String languageId) {
		_tooltipCurrentLanguageId = languageId;
	}

	@Override
	public void setTooltipMap(Map<Locale, String> tooltipMap) {
		setTooltipMap(tooltipMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTooltipMap(
		Map<Locale, String> tooltipMap, Locale defaultLocale) {

		if (tooltipMap == null) {
			return;
		}

		setTooltip(
			LocalizationUtil.updateLocalization(
				tooltipMap, getTooltip(), "Tooltip",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getSynonyms() {
		if (_synonyms == null) {
			return "";
		}
		else {
			return _synonyms;
		}
	}

	@Override
	public void setSynonyms(String synonyms) {
		_synonyms = synonyms;
	}

	@JSON
	@Override
	public String getAttributesJSON() {
		if (_attributesJSON == null) {
			return "";
		}
		else {
			return _attributesJSON;
		}
	}

	@Override
	public void setAttributesJSON(String attributesJSON) {
		_attributesJSON = attributesJSON;
	}

	@JSON
	@Override
	public boolean getStandard() {
		return _standard;
	}

	@JSON
	@Override
	public boolean isStandard() {
		return _standard;
	}

	@Override
	public void setStandard(boolean standard) {
		_standard = standard;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Term.class.getName()));
	}

	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException {

		if (!isInTrash()) {
			return null;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if (Validator.isNotNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			ContainerModel containerModel = null;

			try {
				containerModel = trashHandler.getParentContainerModel(this);
			}
			catch (NoSuchModelException noSuchModelException) {
				return null;
			}

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler =
					com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
						getTrashHandler(
							trashHandler.getContainerModelClassName(
								containerModel.getContainerModelId()));

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(
					containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler() {
		return com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
			getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if ((trashHandler == null) ||
			Validator.isNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			return false;
		}

		try {
			ContainerModel containerModel =
				trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception exception) {
		}

		return false;
	}

	@Override
	public boolean isInTrashExplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return true;
		}

		return false;
	}

	@Override
	public boolean isInTrashImplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return false;
		}

		return true;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Term.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> displayNameMap = getDisplayNameMap();

		for (Map.Entry<Locale, String> entry : displayNameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> definitionMap = getDefinitionMap();

		for (Map.Entry<Locale, String> entry : definitionMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> tooltipMap = getTooltipMap();

		for (Map.Entry<Locale, String> entry : tooltipMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getDisplayName();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			Term.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String displayName = getDisplayName(defaultLocale);

		if (Validator.isNull(displayName)) {
			setDisplayName(
				getDisplayName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setDisplayName(
				getDisplayName(defaultLocale), defaultLocale, defaultLocale);
		}

		String definition = getDefinition(defaultLocale);

		if (Validator.isNull(definition)) {
			setDefinition(getDefinition(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setDefinition(
				getDefinition(defaultLocale), defaultLocale, defaultLocale);
		}

		String tooltip = getTooltip(defaultLocale);

		if (Validator.isNull(tooltip)) {
			setTooltip(getTooltip(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setTooltip(getTooltip(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public Term toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Term>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TermImpl termImpl = new TermImpl();

		termImpl.setUuid(getUuid());
		termImpl.setTermId(getTermId());
		termImpl.setGroupTermId(getGroupTermId());
		termImpl.setGroupId(getGroupId());
		termImpl.setCompanyId(getCompanyId());
		termImpl.setUserId(getUserId());
		termImpl.setUserName(getUserName());
		termImpl.setCreateDate(getCreateDate());
		termImpl.setModifiedDate(getModifiedDate());
		termImpl.setStatus(getStatus());
		termImpl.setStatusByUserId(getStatusByUserId());
		termImpl.setStatusByUserName(getStatusByUserName());
		termImpl.setStatusDate(getStatusDate());
		termImpl.setLastPublishDate(getLastPublishDate());
		termImpl.setTermName(getTermName());
		termImpl.setTermVersion(getTermVersion());
		termImpl.setTermType(getTermType());
		termImpl.setDisplayName(getDisplayName());
		termImpl.setDefinition(getDefinition());
		termImpl.setTooltip(getTooltip());
		termImpl.setSynonyms(getSynonyms());
		termImpl.setAttributesJSON(getAttributesJSON());
		termImpl.setStandard(isStandard());

		termImpl.resetOriginalValues();

		return termImpl;
	}

	@Override
	public int compareTo(Term term) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), term.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Term)) {
			return false;
		}

		Term term = (Term)object;

		long primaryKey = term.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalUserId = _userId;

		_setOriginalUserId = false;

		_setModifiedDate = false;
		_originalStatus = _status;

		_setOriginalStatus = false;

		_originalTermName = _termName;

		_originalTermVersion = _termVersion;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Term> toCacheModel() {
		TermCacheModel termCacheModel = new TermCacheModel();

		termCacheModel.uuid = getUuid();

		String uuid = termCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			termCacheModel.uuid = null;
		}

		termCacheModel.termId = getTermId();

		termCacheModel.groupTermId = getGroupTermId();

		String groupTermId = termCacheModel.groupTermId;

		if ((groupTermId != null) && (groupTermId.length() == 0)) {
			termCacheModel.groupTermId = null;
		}

		termCacheModel.groupId = getGroupId();

		termCacheModel.companyId = getCompanyId();

		termCacheModel.userId = getUserId();

		termCacheModel.userName = getUserName();

		String userName = termCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			termCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			termCacheModel.createDate = createDate.getTime();
		}
		else {
			termCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			termCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			termCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		termCacheModel.status = getStatus();

		termCacheModel.statusByUserId = getStatusByUserId();

		termCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = termCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			termCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			termCacheModel.statusDate = statusDate.getTime();
		}
		else {
			termCacheModel.statusDate = Long.MIN_VALUE;
		}

		Date lastPublishDate = getLastPublishDate();

		if (lastPublishDate != null) {
			termCacheModel.lastPublishDate = lastPublishDate.getTime();
		}
		else {
			termCacheModel.lastPublishDate = Long.MIN_VALUE;
		}

		termCacheModel.termName = getTermName();

		String termName = termCacheModel.termName;

		if ((termName != null) && (termName.length() == 0)) {
			termCacheModel.termName = null;
		}

		termCacheModel.termVersion = getTermVersion();

		String termVersion = termCacheModel.termVersion;

		if ((termVersion != null) && (termVersion.length() == 0)) {
			termCacheModel.termVersion = null;
		}

		termCacheModel.termType = getTermType();

		String termType = termCacheModel.termType;

		if ((termType != null) && (termType.length() == 0)) {
			termCacheModel.termType = null;
		}

		termCacheModel.displayName = getDisplayName();

		String displayName = termCacheModel.displayName;

		if ((displayName != null) && (displayName.length() == 0)) {
			termCacheModel.displayName = null;
		}

		termCacheModel.definition = getDefinition();

		String definition = termCacheModel.definition;

		if ((definition != null) && (definition.length() == 0)) {
			termCacheModel.definition = null;
		}

		termCacheModel.tooltip = getTooltip();

		String tooltip = termCacheModel.tooltip;

		if ((tooltip != null) && (tooltip.length() == 0)) {
			termCacheModel.tooltip = null;
		}

		termCacheModel.synonyms = getSynonyms();

		String synonyms = termCacheModel.synonyms;

		if ((synonyms != null) && (synonyms.length() == 0)) {
			termCacheModel.synonyms = null;
		}

		termCacheModel.attributesJSON = getAttributesJSON();

		String attributesJSON = termCacheModel.attributesJSON;

		if ((attributesJSON != null) && (attributesJSON.length() == 0)) {
			termCacheModel.attributesJSON = null;
		}

		termCacheModel.standard = isStandard();

		return termCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Term, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Term, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Term, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Term)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Term, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Term, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Term, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Term)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Term>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _termId;
	private String _groupTermId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private Date _lastPublishDate;
	private String _termName;
	private String _originalTermName;
	private String _termVersion;
	private String _originalTermVersion;
	private String _termType;
	private String _displayName;
	private String _displayNameCurrentLanguageId;
	private String _definition;
	private String _definitionCurrentLanguageId;
	private String _tooltip;
	private String _tooltipCurrentLanguageId;
	private String _synonyms;
	private String _attributesJSON;
	private boolean _standard;
	private long _columnBitmask;
	private Term _escapedModel;

}